version: '3'

services:
  # Serviço do banco de dados (exemplo usando PostgreSQL)
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: duckappdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - duckapp-network

  # Serviço da sua aplicação Spring Boot
  duckapp:
    image: duckapp:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/duckappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - duckapp-network

networks:
  duckapp-network:
    driver: bridge
